In [1]:
import numpy as np

In [2]:
M = np.matrix([[0,0,0,1],
               [0.5,0,0,0],
              [0.5,0.5,0,0],
              [0,0.5,1,0]])

In [3]:
v = np.matrix([1,1,1,1]).T

In [4]:
M*v

matrix([[ 1. ],
        [ 0.5],
        [ 1. ],
        [ 1.5]])

In [5]:
0.5*M*v+0.5*v/4

matrix([[ 0.625],
        [ 0.375],
        [ 0.625],
        [ 0.875]])

In [6]:
L = np.matrix([[0,1,1,0],
               [0,0,1,1],
              [0,0,0,1],
              [1,0,0,0]])

In [7]:
a = L.T*v
a

matrix([[1],
        [1],
        [2],
        [2]])

In [8]:
L*a

matrix([[3],
        [4],
        [2],
        [1]])

In [9]:
#Flagolet-Martin/Moments
s = 0
n = 55
for i in range(1,11):
    value = (11-i)*i
    s += (n*(2*value-1))
print s/n

430


In [10]:
#PCY Algorithm 
n = 10000
B = 1000
n**2/2/B

50000

In [11]:
50000*4*31/32

193750

In [12]:
#Association-Graph Model 


In [13]:
#Laplacian Matrices 
D = np.diag([2,2,2,3,3,2,2])
A = np.matrix([[0,1,1,0,0,0,0],
             [1,0,0,1,0,0,0],
             [1,0,0,1,0,0,0],
             [0,1,1,0,1,0,0],
             [0,0,0,1,0,1,1],
             [0,0,0,0,1,0,1],
             [0,0,0,0,1,1,0]])
L = D - A
print L

[[ 2 -1 -1  0  0  0  0]
 [-1  2  0 -1  0  0  0]
 [-1  0  2 -1  0  0  0]
 [ 0 -1 -1  3 -1  0  0]
 [ 0  0  0 -1  3 -1 -1]
 [ 0  0  0  0 -1  2 -1]
 [ 0  0  0  0 -1 -1  2]]


In [14]:
#CUR Decomposition 
CUR = np.matrix([[1,2],[3,4],[5,6]])
f = np.linalg.norm(CUR)**2
np.linalg.norm(CUR[:,0])**2/f

0.38461538461538464

In [15]:
#Recommendation Systems 
A = np.array([1,0,1,2.5])
B = np.array([0,1,1,1])
C = np.array([1,1,0,1.5])

print 1 - np.dot(A,B)/(np.linalg.norm(A)*np.linalg.norm(B))
print 1 - np.dot(A,C)/(np.linalg.norm(A)*np.linalg.norm(C))
print A

0.296473529319
0.197819371251
[ 1.   0.   1.   2.5]


In [16]:
#Edit Distance/Clustroids 

In [17]:
#Perceptron/SVM 


In [18]:
#Near-Neighbor Learning 
x = [(1,2),(3,4),(3,1),(4,3)]
y = [1,-1,-1,1]
q = np.array([3.5,1.5])
min_dis = 1e9
label = 0
index = 0
for i in range(0,len(x)):
    point = np.array(x[i])
    dis = np.linalg.norm(point-q)
    print x[i],y[i],dis
    if dis < min_dis:
        min_dis = dis
        label = i
print x[label],y[label]

(1, 2) 1 2.5495097568
(3, 4) -1 2.5495097568
(3, 1) -1 0.707106781187
(4, 3) 1 1.58113883008
(3, 1) -1


In [19]:
#LSH Families 
p1 = 0.7
p2 = 0.3
p1 = p1**2
p2 = p2**2
print 1 - (1-p1)**2
print 1 - (1-p2)**2

0.7399
0.1719
