In [1]:
import numpy as np

# Question 3

In [2]:
eigenvector = [1,3,4,5,7]
eigenvector = eigenvector/np.linalg.norm(eigenvector)
eigenvector

array([ 0.1,  0.3,  0.4,  0.5,  0.7])

# Question 4

In [3]:
M = np.matrix([[1,1],[2,2],[3,4]])

In [4]:
M.T*M

matrix([[14, 17],
        [17, 21]])

# Question 5

In [5]:
M = np.matrix([[1,0,0],[0,2,0],[0,0,0]])
np.linalg.pinv(M)

matrix([[ 1. ,  0. ,  0. ],
        [ 0. ,  0.5,  0. ],
        [ 0. ,  0. ,  0. ]])

# Question 6

In [6]:
M = np.matrix([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [7]:
for i in range(0,4):
    print "The probability of selecting row "+str(i+1)+" is "+str(np.square(M[i]).sum()*1.0/np.square(M).sum())

The probability of selecting row 1 is 0.0215384615385
The probability of selecting row 2 is 0.118461538462
The probability of selecting row 3 is 0.298461538462
The probability of selecting row 4 is 0.561538461538
